export default {
  index: 'Overview',
  'agricultural-engineering': 'Agricultural Engineering',
  'energy-engineering': 'Energy Engineering',
  'applied-engineering': 'Applied Engineering',
  'biomedical-engineering': 'Biomedical Engineering',
  'biological-engineering': 'Biological Engineering',
  'building-services-engineering': 'Building Services Engineering',
  'information-engineering': 'Information Engineering',
  'industrial-engineering': 'Industrial Engineering',
  'mechatronics-engineering': 'Mechatronics Engineering',
  'engineering-management': 'Engineering Management',
  'military-engineering': 'Military Engineering',
  'mining-engineering': 'Mining Engineering',
  'nanoengineering': 'Nanoengineering',
  'quantum-engineering': 'Quantum Engineering',
  'nuclear-engineering': 'Nuclear Engineering',
  'petroleum-engineering': 'Petroleum Engineering',
  'project-engineering': 'Project Engineering',
  'railway-engineering': 'Railway Engineering',
  'software-engineering': 'Software Engineering',
  'supply-chain-engineering': 'Supply Chain Engineering',
  'systems-engineering': 'Systems Engineering',
  'textile-engineering': 'Textile Engineering',
}
